### ISSUE TITLE
[DEPR]: Metrics Dashboard

### ISSUE THREAD

**Issue by e0d** [openedx-unsupported/metrics-dashboard#17]
### Proposal Date

November 14th, 2022

### Target Ticket Acceptance Date

December 1, 2022

### Earliest Open edX Named Release Without This Functionality

N/A

### Rationale

This is a project to customize the GrimoireLabs project to provide metrics about the Open edX project.  

We are now using a [hosted version](https://openedx.biterg.io/app/kibana#/dashboard/Overview) of GrimoireLabs provided by Bitergia.

### Removal

This entire repository would be removed.  This is not a component of the Open edX platform.  Rather, it is back-of-office reporting for open-source projects.

### Replacement

A[ hosted version](https://openedx.biterg.io/app/kibana#/dashboard/Overview) of the same service that is supported and upgraded regularly.

### Additional Info

Post on Discourse: https://discuss.openedx.org/t/deprecation-remove-openedx-metrics-dashboard/8721

**Comment by feanil** [comment]
This was accepted so I'll go through the process of archiving it.

**Comment by feanil** [comment]
I've moved this to edx-unsupported and am closing now prior to archiving this repo.
